name: End-to-end tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pnpm install
        uses: pnpm/action-setup@v2
        # with:
        #   node-version: '10.2.4'
        #   cache: 'npm'
        #   cache-dependency-path: |
        #     web/frontend/package-lock.json
        with:
          #build: pnpm install --no-frozen-lockfile
          version: 8.15.3
          run_install: |
           - recursive: true
             args: [--frozen-lockfile]
        #     build: pnpm install --no-frozen-lockfile
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: web/frontend
          build: npm i -g pnpm
          start: pnpm run dev