name: Testing - main

on:
  pull_request:
      paths:
        - 'web/backend/**'
        - 'piro/**'
        - '.github/workflows/**'
        - 'tests/**'
        - 'requirements.txt'
        - 'setup.py'

jobs:
  build:

    strategy:
      max-parallel: 20
      matrix:
        os: [
          ubuntu-latest,
          windows-latest
        ]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests,m3gnet]
    - name: Install Requirements
      run: |
        pip install -r requirements.txt
    - name: pytest
      env:
        MPLBACKEND: "Agg"
        PMG_MAPI_KEY: "fake_api_key"
      run: |
        pytest tests/unit_tests  --color=yes --cov=piro --cov-report html:coverage_reports
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github
