name: Testing - main

on: [pull_request]

jobs:
  build:

    strategy:
      max-parallel: 20
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest
        ]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests,m3gnet]
        pip install --no-cache-dir pymatgen==2023.9.10
    - name: Check pymatgen installation
      run: |
        pip show pymatgen
        echo "Test Pymatgen version: ${{ steps.check_pymatgen.outputs.version }}"
    - name: pytest
      env:
        MPLBACKEND: "Agg"
        PMG_MAPI_KEY: "fake_api_key"
      run: |
        pytest tests/unit_tests  --color=yes --cov=piro --cov-report html:coverage_reports
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github
