name: Web Testing and Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web/frontend

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - run: pnpm run lint
    - run: pnpm run build --if-present